### ISSUE TITLE
Bot not start: ##File "PokeNoxBot.py", line 1211, in <module>## and other errors

### ISSUE THREAD

**Issue by ardonos** [tellomichmich/PokeNoxBot#48]
`Traceback (most recent call last):
  File "PokeNoxBot.py", line 1211, in <module>
    if CheckTesseract() == False:
  File "PokeNoxBot.py", line 1116, in CheckTesseract
    if ImgToString(img,"PokeNoxBot") == "PokeNoxBot":
  File "D:\POGO\PokeNoxBot-master\Utils.py", line 205, in ImgToString
    img.save("tmp\\ocr.png")
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 1682, in save
    fp = builtins.open(filename, "wb")
IOError: [Errno 2] No such file or directory: 'tmp\\ocr.png'`

Tesseact is installed.

There any mistakes by me?

**Comment by ardonos** [comment]
ok found my mistake.
Have to create the /tmp folder manualy.
